/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * internal/accounts/v1/accounts_internal.proto
 * OpenAPI spec version: version not set
 */

export interface ProtobufAny {
  '@type'?: string;
  [key: string]: unknown;
}
