/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * internal/accounts/v1/accounts_internal.proto
 * OpenAPI spec version: version not set
 */
import type { ProtobufAny } from './protobufAny';

export interface RpcStatus {
  code?: number;
  details?: ProtobufAny[];
  message?: string;
}
