/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * internal/accounts/v1/accounts_internal.proto
 * OpenAPI spec version: version not set
 */

export interface V1LoginResponse {
  access_token?: string;
  expires_in?: number;
  refresh_token?: string;
}
