/**
 * Generated by orval v6.31.0 🍺
 * Do not edit manually.
 * internal/accounts/v1/accounts_internal.proto
 * OpenAPI spec version: version not set
 */

export interface V1User {
  avatar_url?: string;
  id?: string;
  name?: string;
  role?: string;
}
