run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - ineffassign
    - revive

issues:
  exclude-use-default: false

  exclude-rules:
    - path: internal/
      linters:
        - revive

    - path: proto/
      linters:
        - revive
        - errcheck
        - govet
