version: "2"

run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  default: none

  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - gosec
    - unused
    - misspell

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - gosec
          - errcheck

    paths:
      - gen
      - bff/gen
      - api/proto

formatters:
  enable:
    - goimports
