// Package handler provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package handler

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Error   *string `json:"error,omitempty"`
	Message *string `json:"message,omitempty"`
}

// FederatedProvider defines model for FederatedProvider.
type FederatedProvider struct {
	IdentityId    *string    `json:"identity_id,omitempty"`
	LastLoginAt   *time.Time `json:"last_login_at,omitempty"`
	Provider      *string    `json:"provider,omitempty"`
	ProviderEmail *string    `json:"provider_email,omitempty"`
}

// LogoutResponse defines model for LogoutResponse.
type LogoutResponse struct {
	RedirectTo *string `json:"redirect_to,omitempty"`
}

// MeResponse defines model for MeResponse.
type MeResponse struct {
	LoggedIn *bool   `json:"logged_in,omitempty"`
	UserId   *string `json:"user_id,omitempty"`
}

// Profile defines model for Profile.
type Profile struct {
	CreatedAt      *time.Time `json:"created_at,omitempty"`
	Email          *string    `json:"email,omitempty"`
	EmailVerified  *bool      `json:"email_verified,omitempty"`
	FamilyName     *string    `json:"family_name,omitempty"`
	GivenName      *string    `json:"given_name,omitempty"`
	Name           *string    `json:"name,omitempty"`
	NameIsLocal    *bool      `json:"name_is_local,omitempty"`
	Picture        *string    `json:"picture,omitempty"`
	PictureIsLocal *bool      `json:"picture_is_local,omitempty"`
	UpdatedAt      *time.Time `json:"updated_at,omitempty"`
	UserId         *string    `json:"user_id,omitempty"`
}

// Session defines model for Session.
type Session struct {
	CreatedAt  *time.Time `json:"created_at,omitempty"`
	DeviceName *string    `json:"device_name,omitempty"`
	IpAddress  *string    `json:"ip_address,omitempty"`
	IsCurrent  *bool      `json:"is_current,omitempty"`
	LastUsedAt *time.Time `json:"last_used_at,omitempty"`
	SessionId  *string    `json:"session_id,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	Name    *string `json:"name,omitempty"`
	Picture *string `json:"picture,omitempty"`
}

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// AuthCallbackParams defines parameters for AuthCallback.
type AuthCallbackParams struct {
	Code  string `form:"code" json:"code"`
	State string `form:"state" json:"state"`
}

// UpdateProfileJSONRequestBody defines body for UpdateProfile for application/json ContentType.
type UpdateProfileJSONRequestBody = UpdateProfileRequest
